account/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from . import views

app_name = 'account'

urlpatterns = [
    url(r'^personal/(?P<username>.+)/$',
        login_required(views.ProfileView.as_view()), name='index'),

    url(r'^favorites/(?P<username>.+)/$',
        login_required(views.FavoritesView.as_view()), name='favorites'),

    # crafty/follow/2/
    url(r'^follow/(?P<user_id>[0-9]+)/$',
      login_required(views.follow), name='follow'),

    # crafty/follow/2/
    url(r'^unfollow/(?P<user_id>[0-9]+)/$',
      login_required(views.unfollow), name='unfollow'),
]

authentication/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (
    password_reset, password_reset_confirm, password_reset_done)
from django.conf.urls import url
from . import views

app_name = 'authentication'

urlpatterns = [
    # login user
    url(r'^login/$',
        views.LoginView.as_view(), name='login'),

    # logout user
    url(r'^logout/$',
        login_required(views.LogoutView.as_view()), name='logout'),

    # register user
    url(r'^register/$',
        views.RegistrationView.as_view(), name='register'),

    # recover user
    url(r'^password/reset$', password_reset, name='reset_password'),

]

crafty/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from . import views

app_name = 'crafty'

urlpatterns = [

    # crafty home page, "go to views"
    url(r'^explorer/$', login_required(views.ExplorerView.as_view()), name='explorer'),

    # crafty home page, "go to views"
    url(r'^newsfeed/$', login_required(views.NewsfeedView.as_view()), name='newsfeed'),

    # diy details page
    # crafty/2/
    url(r'^(?P<pk>[0-9]+)/$',
        login_required(views.DetailView.as_view()), name='detail'),

    # crafty/diy/add
    url(r'^diy/add/$',
        login_required(views.DiyCreate.as_view()), name='diy-add'),

    # crafty/diy/update/2/
    url(r'^diy/update/(?P<pk>[0-9]+)/$',
      login_required(views.DiyUpdate.as_view()), name='diy-update'),

    # crafty/diy/delete/2/
    url(r'^diy/delete/(?P<pk>[0-9]+)/$',
      login_required(views.DiyDelete.as_view()), name='diy-delete'),

    # crafty/instruction/add/2/
    url(r'^instruction/add/(?P<pk>[0-9]+)/$',
        login_required(views.InstructionCreate.as_view()), name='instruction-add'),

    # crafty/instruction/update/2/
    url(r'^instruction/update/(?P<pk>[0-9]+)/$',
      login_required(views.InstructionUpdate.as_view()), name='instruction-update'),

    # crafty/instruction/delete/2/
    url(r'^instruction/delete/(?P<pk>[0-9]+)/$',
      login_required(views.InstructionDelete.as_view()), name='instruction-delete'),

    # crafty/material/add/2/
    url(r'^material/add/(?P<pk>[0-9]+)/$',
        login_required(views.MaterialCreate.as_view()), name='material-add'),

    # crafty/material/update/2/
    url(r'^material/update/(?P<pk>[0-9]+)/$',
      login_required(views.MaterialUpdate.as_view()), name='material-update'),

    # crafty/material/delete/2/
    url(r'^material/delete/(?P<pk>[0-9]+)/$',
      login_required(views.MaterialDelete.as_view()), name='material-delete'),

    # crafty/favorite/2/
    url(r'^favorite/(?P<diy_id>[0-9]+)/$',
      login_required(views.favorite), name='favorite'),

    # crafty/unfavorite/2/
    url(r'^unfavorite/(?P<diy_id>[0-9]+)/$',
      login_required(views.unfavorite), name='unfavorite'),

    # crafty/copywrite
    url(r'^copyright/$',
      login_required(views.CopyrightView.as_view()), name='copyright'),

]

website/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from django.contrib.auth.views import password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(url=reverse_lazy('crafty:newsfeed'))),
    url(r'^admin/', admin.site.urls),
    url(r'^crafty/', include('crafty.urls', namespace="crafty")), 
    url(r'^profile/', include('account.urls', namespace="profile")), 
    url(r'^accounts/', include('authentication.urls', namespace="auth")),

    # reset confirmation
    url(r'^password/reset/done$',
        password_reset_done, name='password_reset_done'),

    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm, name='password_reset_confirm'),

    url(r'^password/reset/complete/$',
        password_reset_complete, name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crafty/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models

class SkillLevel(models.Model):
  level = models.CharField(max_length=15)

  def __str__(self):
    return self.level

class Category(models.Model):
  category = models.CharField(max_length=50)

  def __str__(self):
    return self.category

class TimeUnits(models.Model):
  unit = models.CharField(max_length=15)

  def __str__(self):
    return self.unit

class Diy(models.Model):
  title = models.CharField(max_length=500)
  description = models.CharField(max_length=1000)
  skill_level = models.ForeignKey(SkillLevel, on_delete=models.CASCADE)
  category = models.ForeignKey(Category, on_delete=models.CASCADE)
  duration = models.IntegerField()
  duration_units = models.ForeignKey(TimeUnits, on_delete=models.CASCADE)
  picture = models.ImageField(null=True)
  creator = models.ForeignKey(User, on_delete=models.CASCADE)

  def get_absolute_url(self):
    return reverse('crafty:detail', kwargs={'pk': self.pk})

  def __str__(self):
    return self.title + " - " + self.creator.username

class Material(models.Model):
  name = models.CharField(max_length=100)
  amount = models.IntegerField()
  units = models.CharField(max_length=20, null=True)
  diy = models.ForeignKey(Diy, on_delete=models.CASCADE)

  def get_absolute_url(self):
    return self.diy.get_absolute_url()

  def __str__(self):
    return str(self.amount) + " " + self.units + " of " + self.name

class Instruction(models.Model):
  instruction = models.CharField(max_length=1000)
  picture = models.ImageField(null=True)
  diy = models.ForeignKey(Diy, on_delete=models.CASCADE)

  def get_absolute_url(self):
    return self.diy.get_absolute_url()

  def __str__(self):
    return self.instruction

class Favorite(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  diy = models.ForeignKey(Diy, on_delete=models.CASCADE)

class Comment(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  diy = models.ForeignKey(Diy, on_delete=models.CASCADE)
  comment = models.CharField(max_length=1000)

crafty/forms/diyForm.py
from crafty.models import Diy
from django import forms

class DiyForm(forms.ModelForm):
    class Meta:
        model = Diy
        exclude = ['creator']

    def __init__(self, *args, **kwargs):
        super(DiyForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].help_text = None

crafty/forms/instructionForm.py
from crafty.models import Instruction
from django import forms

class InstructionForm(forms.ModelForm):
    class Meta:
        model = Instruction
        exclude = ["diy"]

    def __init__(self, *args, **kwargs):
        super(InstructionForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].help_text = None

crafty/forms/materialForm.py
from crafty.models import Material
from django import forms

class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        exclude = ["diy"]

    def __init__(self, *args, **kwargs):
        super(MaterialForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].help_text = None

crafty/forms/userForm.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['confirm_password'] = forms.CharField()
        self.fields['confirm_password'].widget = forms.PasswordInput()

        for key in self.fields:
            self.fields[key].help_text = None
            self.fields[key].required = True

crafty/views.py
from django.contrib.auth import authenticate, login, logout, REDIRECT_FIELD_NAME
from django.contrib.auth.forms import AuthenticationForm
from django.core.urlresolvers import reverse_lazy
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.views import generic
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import View, FormView, RedirectView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect, get_object_or_404
from account.models import Follow
from .forms.diyForm import DiyForm
from .forms.instructionForm import InstructionForm
from .forms.materialForm import MaterialForm
from .models import Diy, Instruction, Material, Favorite

class ExplorerView(generic.ListView):
    template_name='crafty/index.html'
    context_object_name = 'diys'

    def get_queryset(self):
        queryset =  Diy.objects.all().annotate(num_likes=Count('favorite')).order_by('-num_likes')
        for item in queryset:
            item.favorite = item.favorite_set.filter(user=self.request.user).count() == 0
        return queryset

class NewsfeedView(generic.ListView):
    template_name='crafty/index.html'
    context_object_name = 'diys'

    def get_queryset(self):
        follows = Follow.objects.filter(follower=self.request.user)
        users = []
        for follow in follows:
            users.append(follow.followee)

        queryset =  Diy.objects.filter(creator__in=users).annotate(num_likes=Count('favorite')).order_by('-pk')
        for item in queryset:
            item.favorite = item.favorite_set.filter(user=self.request.user).count() == 0
        return queryset

class DetailView(generic.DetailView):
    model = Diy
    template_name = 'crafty/details.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        diy = Diy.objects.get(pk=int(self.kwargs['pk']))
        diy.materials = diy.material_set.all().order_by('pk')
        diy.hasMaterials = diy.material_set.count() > 0
        diy.instructions = diy.instruction_set.all().order_by('pk')
        diy.hasInstructions = diy.instruction_set.count() > 0
        context['diy'] = diy
        return context

class DiyCreate(CreateView):
    model = Diy
    form_class = DiyForm

    def form_valid(self, form):
        diy = form.save(commit=False)
        diy.creator = self.request.user
        diy.save()
        return HttpResponseRedirect(diy.get_absolute_url())

class DiyUpdate(UpdateView):
    model = Diy
    fields = ["title", "description", "skill_level", "category", "duration", "duration_units", "picture"]

class DiyDelete(DeleteView):
    model = Diy
    success_url = reverse_lazy('crafty:explorer')

class InstructionCreate(CreateView):
    model = Instruction
    form_class = InstructionForm

    def form_valid(self, form):
        instruction = form.save(commit=False)
        diy = Diy.objects.get(pk=int(self.kwargs['pk']))
        instruction.diy = diy
        instruction.save()
        return HttpResponseRedirect(diy.get_absolute_url())

class InstructionUpdate(UpdateView):
    model = Instruction
    fields = ['instruction', 'picture']

class InstructionDelete(DeleteView):
    model = Instruction

    def get_success_url(self):
        instruction = Instruction.objects.get(pk=int(self.kwargs['pk']))
        return instruction.diy.get_absolute_url()

class MaterialCreate(CreateView):
    model = Material
    form_class = MaterialForm

    def form_valid(self, form):
        material = form.save(commit=False)
        diy = Diy.objects.get(pk=int(self.kwargs['pk']))
        material.diy = diy
        material.save()
        return HttpResponseRedirect(diy.get_absolute_url())

class MaterialUpdate(UpdateView):
    model = Material
    fields = ['name', 'amount', 'units']

    def form_valid(self, form):
        material = form.save(commit=False)
        material.save()
        return HttpResponseRedirect(material.diy.get_absolute_url())

class MaterialDelete(DeleteView):
    model = Material

    def get_success_url(self):
        material = Material.objects.get(pk=int(self.kwargs['pk']))
        return material.diy.get_absolute_url()

def favorite(request, diy_id):
    diy = get_object_or_404(Diy, pk=diy_id)
    Favorite.objects.create(diy=diy, user=request.user)
    return HttpResponseRedirect(request.POST['url'])

def unfavorite(request, diy_id):
    diy = get_object_or_404(Diy, pk=diy_id)
    Favorite.objects.filter(diy=diy, user=request.user).delete()
    return HttpResponseRedirect(request.POST['url'])

class CopyrightView(TemplateView):
    template_name = "crafty/copywrite.html"

crafty/templates/crafty/base.html
<!DOCTYPE html>
<html>
<head>
  {% block title %}
    <title>Crafty</title>
  {% endblock %}
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'crafty/style.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="{% static 'crafty/scripts.js' %}"></script>
  <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
</head>
<body>
  {% block nav %}
  {% endblock %}
  {% block body %}
  {% endblock %}
  {% block extras %}
  {% endblock %}
</body>
</html>

crafty/templates/crafty/confirm_delete.html
{% extends 'crafty/base.html' %}

{% block body %}
  <div class="flex-container container-fluid">
    <div class="flex-row row">
      <div class="panel panel-default center-panel">
        <div class="panel-body">
          <form action="" method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" value="Confirm" />
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

crafty/templates/crafty/copywrite.html
{% extends 'crafty/base.html' %}

{% block nav %}
  {% include 'crafty/nav.html' %}
{% endblock %}

{% block body %}
  <div class="container-fluid">
    <div class="row">
      <div class="panel panel-default center-panel">
        <div class="panel-body">
          <h1>Copyright Business Professionals of America</h1>
          <h2>Area 1 Region 3</h2>
          {% load staticfiles %}
          <img src="{%  static 'crafty/logo.png' %}">
          <h3>Participants</h3>
          <p>Ananya Ramkumar</p>
          <p>An Nguyen</p>
          <p>Britney Lam</p>
          <p>Ethan Beauregard</p>
          <h3>DIY Website</h3>
          <p>Plano West Senior High School</p>
          <p>Plano, TX</p>
          <p>2016-2017</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

crafty/templates/crafty/create_form_template.html
{% extends 'crafty/base.html' %}

{% block title %}
{% endblock %}

{% block nav %}
  {% include 'crafty/nav.html' %}
{% endblock %}

{% block body %}
  <div class="container-fluid">
    <div class="row">
      <div class="panel panel-default center-panel">
        <div class="panel-body">
          {% block panelTitle %}
          {% endblock %}
          {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
          {% endif %}
          <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'crafty/form_template.html' %}
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

crafty/templates/crafty/details.html
{% extends 'crafty/base.html' %}

{% block title %}
  <title>{{ diy }}</title>
{% endblock %}

{% block nav %}
  {% include 'crafty/nav.html' %}
{% endblock %}

{% block body %}
  <div class="details-panel">
    <h1>{{ diy.title }} <span class="diy-category">{{diy.category}}</span></h1>
    <a href="{% url 'profile:index' diy.creator.username %}">
      <h2>{{ diy.creator.first_name }} {{ diy.creator.last_name }}</h2>
    </a>
    <div class="general-info">
      <span class="diy-skill-level">{{diy.skill_level}}</span>
      <span class="diy-duration">{{diy.duration}} {{diy.duration_units}}</span>
      {% if diy.favorite_set.count == 1 %}
        <span class="diy-like">{{diy.favorite_set.count}} like</span>
      {% else %}
        <span class="diy-like">{{diy.favorite_set.count}} likes</span>
      {% endif %}
    </div>
    <div class="diy-image wedge">
     <img src="{{diy.picture.url}}">
    </div>
    <h3>Description</h3>
    <p>{{ diy.description }}</p>
    <h3>Materials</h3>
    {% if diy.hasMaterials %}
      <table class="material-list">
        {% for material in diy.materials %}
          <tr class="material-item">
            <td class="material-name">{{material.name}}</td>
            <td class="material-amount">{{material.amount}} {{material.units}}</td>
            {% if diy.creator.username == request.user.username %}
              <td>
                <a class="material-update-delete" href="{% url 'crafty:material-update' material.id %}">
                  <button type="submit" class="btn material-update">
                    <span class="glyphicon glyphicon-pencil"></span>
                  </button>
                </a>
              </td>
              <td>
                <form action="{% url 'crafty:material-delete' material.id %}" class="material-update-delete inline-form">
                  {% csrf_token %}
                  <input type="hidden" name="diy_id" value="{{ diy.id }}">
                  <button type="submit" class="btn btn-trash material-trash">
                    <span class="glyphicon glyphicon-trash"></span>
                  </button>
                </form>
              </td>
            {% endif %}
          </tr>
        {% endfor %}
      </table>
    {% endif %}
    {% if diy.creator.username == request.user.username %}
      <a class="add-container" href="{% url 'crafty:material-add' diy.id %}">
        <button class="add-material-button">Add Material</button>
      </a>
    {% endif %}
    <h3>Instructions</h3>
    {% if diy.hasInstructions %}
      <ol class="instruction-list">
        {% for instruction in diy.instructions %}
          <li>
            {% if diy.creator.username == request.user.username %}
              <a href="{% url 'crafty:instruction-update' instruction.id %}">
                <button type="submit" class="btn instruction-update">
                  <span class="glyphicon glyphicon-pencil"></span>
                </button>
              </a>
              <form action="{% url 'crafty:instruction-delete' instruction.id %}" class="inline-form">
                {% csrf_token %}
                <input type="hidden" name="diy_id" value="{{ diy.id }}">
                <button type="submit" class="btn btn-trash instruction-trash">
                  <span class="glyphicon glyphicon-trash"></span>
                </button>
              </form>
            {% endif %}
            <div class="instruction-item">
              {% if instruction.picture %}
                <img src="{{instruction.picture.url}}">
              {% endif %}
              <div>{{instruction.instruction}}</div>
            </div>
          </li>
        {% endfor %}
      </ol>
    {% endif %}
    {% if diy.creator.username == request.user.username %}
      <a class="add-container" href="{% url 'crafty:instruction-add' diy.id %}">
        <button class="add-instruction-button">Add Instruction</button>
      </a>
    {% endif %}
  </div>
{% endblock %}

crafty/templates/crafty/diy-list-item.html
<div class="diy-list-item">
  <a href="{% url 'crafty:detail' diy.id %}">
    <div class="diy-panel panel panel-default">
      <div class="panel-body">
        <img src="{{ diy.picture.url }}" />
        <h1>{{diy.title}}</h1>
        <h2><a href="{% url 'profile:index' diy.creator.username %}">{{diy.creator.username}}</a></h2>
        {% if diy.num_likes == 1 %}
          <div>{{diy.num_likes}} like</div>
        {% else %}
          <div>{{diy.num_likes}} likes</div>
        {% endif %}
        <div class="align-flex">
          {% if diy.favorite %}
            <form action="{% url 'crafty:favorite' diy.id %}" class="inline-form" method="post">
              {% csrf_token %}
              <input type="hidden" name="diy_id" value="{{ diy.id }}">
              <input type="hidden" name="url" value="{{ request.get_full_path }}">
              <button type="submit" class="btn btn-favorite">
                <span class="glyphicon glyphicon glyphicon-star-empty"></span>
              </button>
            </form>
          {% else %}
            <form action="{% url 'crafty:unfavorite' diy.id %}" class="inline-form" method="post">
              {% csrf_token %}
              <input type="hidden" name="diy_id" value="{{ diy.id }}">
              <input type="hidden" name="url" value="{{ request.get_full_path }}">
              <button type="submit" class="btn btn-favorite">
                <span class="glyphicon glyphicon glyphicon-star"></span>
              </button>
            </form>
          {% endif %}
          {% if diy.creator.username == request.user.username %}
            <form action="{% url 'crafty:diy-delete' diy.id %}" class="inline-form">
              {% csrf_token %}
              <input type="hidden" name="diy_id" value="{{ diy.id }}">
              <button type="submit" class="btn btn-trash">
                <span class="glyphicon glyphicon-trash"></span>
              </button>
            </form>
          {% endif %}
        </div>
      </div>
    </div>
  </a>
</div>

crafty/templates/crafty/diy_confirm_delete.html
<form action="" method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm" />
</form>

crafty/templates/crafty/diy_form.html
{% extends 'crafty/base.html' %}

{% block title %}
  <title>Create New DIY</title>
{% endblock %}

{% block nav %}
  {% include 'crafty/nav.html' %}
{% endblock %}

{% block body %}
  <div class="container-fluid">
    <div class="row">
      <div class="panel panel-default center-panel">
        <div class="panel-body">
          <h3>Create New DIY</h3>
          {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
          {% endif %}
          <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'crafty/form_template.html' %}
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

crafty/templates/crafty/form_template.html
{% for field in form %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <div class="col-sm-12 align-flex">
      <label class="control-label col-sm-2">{{ field.label_tag }}</label>
      <div class="col-sm-10">{{ field }}</div>
    </div>
  </div>
{% endfor %}

crafty/templates/crafty/index.html
{% extends 'crafty/base.html' %}

{% block nav %}
  {% include 'crafty/nav.html' %}
{% endblock %}

{% block body %}
  {% if diys %}
    <div id="diy-list">
      {% for diy in diys %}
        {% include 'crafty/diy-list-item.html' %}
      {% endfor %}
    </div>
  {% else %}
    <h3>No DIYs to show</h3>
  {% endif %}
{% endblock %}

{% block extras %}
  <div class="fixedPositioningButtons">
    <a href="{% url 'crafty:diy-add' %}">
      <button class="add-button">
        <span class="glyphicon glyphicon-plus"></span>
      </button>
    </a>
<!--     <a href="{% url 'crafty:diy-add' %}">
      <button class="filter-button">
        <span class="glyphicon glyphicon-filter"></span>
      </button>
    </a> -->
  </div>
{% endblock %}

crafty/templates/crafty/instruction_form.html
{% extends 'crafty/create_form_template.html' %}

{% block title %}
  <title>Add New Instruction</title>
{% endblock %}

{% block panelTitle %}
  <h3>Add New Instruction</h3>
{% endblock %}

crafty/templates/crafty/material_confirm_delete.html
{% extends 'crafty/confirm_delete.html' %}

crafty/templates/crafty/material_form.html
{% extends 'crafty/create_form_template.html' %}

{% block title %}
  <title>Add New Material</title>
{% endblock %}

{% block panelTitle %}
  <h3>Add New Material</h3>
{% endblock %}

crafty/templates/crafty/nav.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-target" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'crafty:explorer' %}">Crafty</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse-target">
      <ul class="nav navbar-nav">
        <li {% if 'explorer' in request.path %}class="active"{% endif %}>
          <a href="{% url 'crafty:explorer' %}">
            <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp; Explorer
          </a>
        </li>
        <li {% if 'newsfeed' in request.path %}class="active"{% endif %}>
          <a href="{% url 'crafty:newsfeed' %}">
            <span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span>&nbsp; Newsfeed
          </a>
        </li>
      </ul>
<!--       <form class="navbar-form navbar-left" role="search" method="get" action="#">
        <div class="form-group-height">
          <input type="text" class="form-control search-query" name="query" placeholder="Search"><button type="submit" class="btn btn-default search-btn search-button"><span class="glyphicon glyphicon-search"></span></button>
        </div>
      </form> -->

      <ul class="nav navbar-nav navbar-right">
        <li {% if 'favorites/' in request.path and request.user.username in request.path %}class="active"{% endif %}>
          <a href="{% url 'profile:favorites' request.user.username %}">
             <span class="glyphicon glyphicon-star" aria-hidden="true"></span>&nbsp; My Favorites
          </a>
        </li>
        <li {% if 'personal/' in request.path and request.user.username in request.path %}class="active"{% endif %}>
          <a href="{% url 'profile:index' request.user.username %}">
             <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; {{ request.user.first_name }}
          </a>
        </li>
        <li {% if 'copyright' in request.path %}class="active"{% endif %}>
          <a href="{% url 'crafty:copyright' %}">
             <span class="glyphicon glyphicon-copyright-mark" aria-hidden="true"></span>&nbsp; Copyright
          </a>
        </li>
        <li class="">
          <a href="{% url 'auth:logout' %}">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>